Models/Bowler.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Bowling.Models
{
    public class Bowler
    {
        
        [Key]
        [Required]
        public int BowlerID { get; set; }

        // Max Length pieces are to meet the original DB requirements
        [MaxLength(40)]
        public string BowlerLastName { get; set; }

        [MaxLength(40)]
        public string BowlerFirstName { get; set; }

        [MaxLength(40)]
        public string BowlerMiddleInit { get; set; }

        [MaxLength(50)]
        public string BowlerAddress { get; set; }

        [MaxLength(40)]
        public string BowlerCity { get; set; }

        [MaxLength(2)]
        public string BowlerState { get; set; }

        [MaxLength(10)]
        public string BowlerZip { get; set; }

        [MaxLength(14)]
        public string BowlerPhoneNumber { get; set; }

        public int TeamID { get; set; }
        public Team Team { get; set; }

    }
}

Models/BowlersDbContext.cs
using System;
using Microsoft.EntityFrameworkCore;

namespace Bowling.Models
{
    public class BowlersDbContext : DbContext
    {
       public BowlersDbContext(DbContextOptions<BowlersDbContext> options) : base (options)
        {

        }

        public DbSet<Bowler> Bowlers { get; set; }

        public DbSet<Team> Teams { get; set; }
    }
}

Models/EFBowlerRepository.cs
using System;
using System.Linq;

namespace Bowling.Models
{
    public class EFBowlerRepository : IBowlerRepository
    {
        private BowlersDbContext _context { get; set; }


        public EFBowlerRepository ( BowlersDbContext temp)
        {
            _context = temp;
        }


        public IQueryable<Bowler> Bowlers => _context.Bowlers;

        public IQueryable<Team> Teams => _context.Teams;


        //CRUD Functions
        public void SaveBowler(Bowler b)
        {
            _context.Update(b);
            _context.SaveChanges();
        }

        public void CreateBowler(Bowler b)
        {
            _context.Add(b);
            _context.SaveChanges();
        }

        public void DeleteBowler(Bowler b)
        {
            _context.Remove(b);
            _context.SaveChanges();
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Bowling.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/IBowlerRepository.cs
using System;
using System.Linq;

namespace Bowling.Models
{
    public interface IBowlerRepository
    {
        IQueryable<Bowler> Bowlers { get;  }

        IQueryable<Team> Teams { get;  }


        public void SaveBowler(Bowler b);

        public void CreateBowler(Bowler b);

        public void DeleteBowler(Bowler b);
    }
}

Models/Team.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Bowling.Models
{
    public class Team
    {
       [Key]
       [Required]
       public int TeamID { get; set; }

        public string TeamName { get; set; }

        public int CaptainID { get; set; }
    }
}

Components/TeamsViewComponent.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Bowling.Models;
using Microsoft.EntityFrameworkCore;


// See /Shared/Componenets/Teams/Defaul.cshtml to see the View
namespace Bowling.Components
{
    public class TeamsViewComponent : ViewComponent
    {
        
        private IBowlerRepository repo;

        public TeamsViewComponent(IBowlerRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedTeam = RouteData?.Values["teamName"];
          

            var teams = repo.Bowlers
                .Include(x => x.Team)
                .Select(x => x.Team)
                .Distinct()
                .OrderBy(x => x)
                .ToList();
                

            return View(teams);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Bowling.Models;
using Microsoft.EntityFrameworkCore;

namespace Bowling.Controllers
{
    public class HomeController : Controller
    {

        private IBowlerRepository _repo { get; set; }


        public HomeController(IBowlerRepository temp)
        {
            _repo = temp;
        }

        public IActionResult Index()
        {


            return View();
        }

        public IActionResult Bowlers(string teamName)
        {
            var bowlers = _repo.Bowlers
                .Include(x => x.Team)
                .Where(x => x.Team.TeamName == teamName || teamName == null)
                .ToList();

            ViewBag.Team = teamName;


            return View(bowlers);
        }


        [HttpGet]
        public IActionResult EditBowler(int bowlerId)
        {
            var bowler = _repo.Bowlers.FirstOrDefault(x => x.BowlerID == bowlerId);

            ViewBag.Teams = _repo.Teams.ToList();

            return View(bowler);

        }
        [HttpPost]
        public IActionResult EditBowler(Bowler b)
        {
            if (ModelState.IsValid)
            {
                
                _repo.SaveBowler(b);

                var bowlers = _repo.Bowlers
                .Include(x => x.Team)
                .ToList();

                return View("Bowlers", bowlers);
            }
            else
            {
                var bowler = _repo.Bowlers.FirstOrDefault(x => x.BowlerID == b.BowlerID);

                ViewBag.Teams = _repo.Teams.ToList();

                return View(bowler);
            }
        }

        [HttpGet]
        public IActionResult AddBowler()
        {
           
            ViewBag.Teams = _repo.Teams.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult AddBowler(Bowler b)
        {
           
            if (ModelState.IsValid)
            {
                _repo.CreateBowler(b);
                var bowlers = _repo.Bowlers
                .Include(x => x.Team)
                .ToList();

                return View("Bowlers", bowlers);
            }
            else
            {
                ViewBag.NewId = _repo.Bowlers.Count() + 1;
                ViewBag.Teams = _repo.Teams.ToList();
                return View();
            }
           
        }


        [HttpGet]
        public IActionResult DeleteBowler (int bowlerId)
        {

            var bowler = _repo.Bowlers.FirstOrDefault(x => x.BowlerID == bowlerId);
           

            return View(bowler);
        }
        [HttpPost]
        public IActionResult DeleteBowler (Bowler b)
        {

            _repo.DeleteBowler(b);
            var bowlers = _repo.Bowlers
                .Include(x => x.Team)
                .ToList();

            return View("Bowlers", bowlers);
        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/AddBowler.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Bowler


<h3>Add Bowler</h3>

<form method="post">

    <div class="form-group">
        <input type="hidden" asp-for="BowlerID"  disabled />
    </div>

    <div class="form-group">
        <label asp-for="BowlerFirstName">First Name</label>
        <input asp-for="BowlerFirstName" type="text"  />
    </div>

    <div class="form-group">
        <label asp-for="BowlerMiddleInit">Middle Initial</label>
        <input asp-for="BowlerMiddleInit" type="text"  />
    </div>

    <div class="form-group">
        <label asp-for="BowlerLastName">Last Name</label>
        <input asp-for="BowlerLastName" type="text" />
    </div>

    <div class="form-group">
        <label asp-for="BowlerAddress">Address</label>
        <input asp-for="BowlerAddress" type="text" />
    </div>

    <div class="form-group">
        <label asp-for="BowlerCity">City</label>
        <input asp-for="BowlerCity" type="text"/>
    </div>

    <div class="form-group">
        <label asp-for="BowlerState">State</label>
        <input asp-for="BowlerState" type="text"/>
    </div>

    <div class="form-group">
        <label asp-for="BowlerZip">Zipcode</label>
        <input asp-for="BowlerZip" type="text" />
    </div>

    <div class="form-group">
        <label asp-for="BowlerPhoneNumber">Phone Number</label>
        <input asp-for="BowlerPhoneNumber" type="text"  />
    </div>

    <div class="form-group">
        <label asp-for="Team">Team</label>
        <select asp-for="TeamID">
            @foreach (Team t in ViewBag.Teams)
            {
                <option value="@t.TeamID">@t.TeamName</option>
            }
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Save Changes</button>

    <div asp-validation-summary="All"></div>


</form>

Views/Home/Bowlers.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model List<Bowler>

<h4>@ViewBag.Team</h4>

    <div class="d-flex">
<table class="table table-bordered table-striped m-1 p-1">
    <thead>
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip</th>
            <th>Phone</th>
            <th>Team Name</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var b in Model)
        {
        <tr>
            <td>@b.BowlerFirstName @b.BowlerMiddleInit @b.BowlerLastName</td>
            <td>@b.BowlerAddress</td>
            <td>@b.BowlerCity</td>
            <td>@b.BowlerState</td>
            <td>@b.BowlerZip</td>
            <td>@b.BowlerPhoneNumber</td>
            <td>@b.Team.TeamName</td>
            <td><a asp-controller="Home" asp-action="EditBowler" asp-route-bowlerId="@b.BowlerID" class="btn btn-sm btn-warning">Edit</a></td>
            <td><a asp-controller="Home" asp-action="DeleteBowler" asp-route-bowlerId="@b.BowlerID" class="btn btn-sm btn-danger">Delete</a></td>
        </tr>
        }
    </tbody>

    </table>

    <div class="m-1 p-1">
        <vc:teams></vc:teams>
    </div>

    </div>

<div>
    <a asp-controller="Home" asp-action="AddBowler" class="btn btn-primary">Add Bowler </a>
</div>

Views/Home/DeleteBowler.cshtml
@model Bowler

<h3>Are you sure you want to delete the record for @Model.BowlerFirstName @Model.BowlerLastName?</h3>
<form method="post">
    <input type="hidden" asp-for="BowlerID" />
    <button class="btn btn-danger" type="submit">Delete</button>
    <a asp-controller="Home" asp-action="Bowlers" class="btn btn-primary">Cancel</a>
</form>

Views/Home/EditBowler.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Bowler

<h3>Edit Bowler</h3>

<form method="post">

    <div class="form-group">
        <input type="hidden" asp-for="BowlerID" disabled />
    </div>


    <div class="form-group">
        <label asp-for="BowlerFirstName">First Name</label>
        <input asp-for="BowlerFirstName" type="text" value="@Model.BowlerFirstName" />
    </div>

    <div class="form-group">
        <label asp-for="BowlerMiddleInit">Middle Initial</label>
        <input asp-for="BowlerMiddleInit" type="text" value="@Model.BowlerMiddleInit" />
    </div>

    <div class="form-group">
        <label asp-for="BowlerLastName">Last Name</label>
        <input asp-for="BowlerLastName" type="text" value="@Model.BowlerLastName" />
    </div>

    <div class="form-group">
        <label asp-for="BowlerAddress">Address</label>
        <input asp-for="BowlerAddress" type="text" value="@Model.BowlerAddress" />
    </div>

    <div class="form-group">
        <label asp-for="BowlerCity">City</label>
        <input asp-for="BowlerCity" type="text" value="@Model.BowlerCity" />
    </div>

    <div class="form-group">
        <label asp-for="BowlerState">State</label>
        <input asp-for="BowlerState" type="text" value="@Model.BowlerState" />
    </div>


    <div class="form-group">
        <label asp-for="BowlerZip">Zipcode</label>
        <input asp-for="BowlerZip" type="text" value="@Model.BowlerZip" />
    </div>

    <div class="form-group">
        <label asp-for="BowlerPhoneNumber">Phone Number</label>
        <input asp-for="BowlerPhoneNumber" type="text" value="@Model.BowlerPhoneNumber" />
    </div>

    <div class="form-group">
        <label asp-for="Team">Team</label>
        <select asp-for="TeamID">
            @foreach (Team t in ViewBag.Teams)
            {
                <option value="@t.TeamID">@t.TeamName</option>
            }
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Save Changes</button>

    <div asp-validation-summary="All"></div>


</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To Bowling Stuff</h1>
    
</div>

Views/Shared/Components/Teams/Default.cshtml
@{
}

@model List<Team>


@*See /Componenets/TeamsViewComponenet for corresponding View Componenet*@


<div>
    <a asp-controller="Home" asp-action="Bowlers" asp-route-teamName="">Home</a>
</div>

@foreach (Team t in Model)
{
    <div>
        <a asp-controller="Home" asp-action="Bowlers" asp-route-teamName="@t.TeamName" 
           class="btn @(ViewBag.SelectedTeam == t.TeamName ? "btn-primary" : "btn-outline-secondary")">
        @t.TeamName
        </a>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bowling</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bowling</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Bowlers">Bowlers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bowling 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>